version: "3.9"

services:
  frontend-app:
    container_name: frontend-app
    restart: "always"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - PORT=3001
      - DEBUG=lightray*
    ports:
      - 3001:3001
